_welcome:
    pattern: /
    defaults: { _controller: AYGeneralBundle:Default:index }

homepage:
    pattern:  /index
    defaults: { _controller: AYGeneralBundle:Default:index }

number:
    pattern:  /number/{number}
    defaults: { _controller: AYGeneralBundle:Default:number }

search_number:
    pattern:  /search_number
    defaults: { _controller: AYGeneralBundle:Default:searchNumber }

# API

api_post_message:
    pattern:  /api/message/post
    defaults: { _controller: AYGeneralBundle:Default:postMessage }

api_update_message:
    pattern:  /api/message/update
    defaults: { _controller: AYGeneralBundle:Default:updateMessage }
